# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


GMAIL_USERNAME: 'akbar.hussain@devsinc.com'
GMAIL_PASSWORD: 'azlwsodwdojnvyuc'

CLOUDINARY_CLOUD_NAME: "instagram-dev"
CLOUDINARY_API_KEY: "485279143991815"
CLOUDINARY_API_SECRET: "XPhQX0eisU09BR3mzA_kBxGO2i4"

REDIS_HOSTNAME: redis-15080.c1.asia-northeast1-1.gce.cloud.redislabs.com
REDIS_PORT: 15080
REDIS_PASSWORD: xQUfoAXNfnHpciwAmoXpRNzk7fTHA4TZ