development:
  adapter: redis
  url: <%= ENV['REDIS_END_POINT'] %>

test:
  adapter: async

production:
  adapter: redis
  url: rediss://:5TCpwKXm5B4TRD8eq4DmCTEGbGsOXp8X@redis-10720.c1.asia-northeast1-1.gce.cloud.redislabs.com:10720
  channel_prefix: instagram_production
