default: &default
  host: 'localhost'
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: instagram
  username: admin
  password: 123123

production:
  <<: *default
  database: production_instagram
  username: admin
  password: 123123

test:
  <<: *default
  database: testing_instagram
  username: admin
  password: 123123